[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "cyan"

[runner]
fastReruns = true

[server]
# Run in headless mode (no GUI interface)
headless = false

